demo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('',views.firstpave,name='pass')
]

doxer_admin/urls.py
from django.urls import path
from . import views


app_name = "doxer_admin"

urlpatterns = [
    path('login-page/',views.LoginPage,name='loginpage'),
    path('',views.home,name='indexpage'),
    path('all-drivers/',views.All_Drivers,name='alldrivers'),
    path('all-passengers/',views.All_Passengers,name='allpassenger'),
    path('all-cars/',views.All_Cars,name='allcars'),
    path('all-rides/',views.All_Rides,name='allrides'),
    path('city-rides/',views.with_in_city_Rides,name='cityrides'),
    path('accepted-cars/',views.Accepted_Cars,name='acceptedcar'),
    path('rejected-cars/',views.Rejected_Cars,name='rejectedcar'),
    
    path('manage-brands-&-<str:tt>-Models/',views.manage_brand,name='manage_brand'),
    path('brand-<str:tt>-store/',views.add_brand_store,name='add_brand_store'),
    path('store-<str:tt>-Models/',views.add_vehical_store,name='add_vehical_store'),
    path('delete-<str:tt>-brand/<str:data>/',views.DeteleVehical_brand,name='DeteleVehical_brand'),
    path('delete-<str:tt>-Models/<str:data>/',views.DeteleCar_name,name='DeteleCar_name'),
    
    # path('admin-add-form/',views.Add_Driver_Form,name='driverform'),
    
    path('Car-accepted/',views.car_accept,name='caraccept'),
    path('Car-rejected/',views.car_reject,name='carreject'),
    path('block-unblock-passenger/',views.BlockPassenger,name='blockpas'),
    path('block-unblock-driver/',views.BlockDriver,name='blockdri'),
    path('edit-price/',views.editprice,name='editprices'),
    path('edit-editcar/',views.editcar,name='editcar'),
    path('show-User-ID/<str:pk>',views.Id_proofes,name='showid'),
    path('Approval-ID/<str:pk>',views.Id_Approval,name='Id_Approval'),
    path('update-price/',views.updateprice,name='updatepriceb'),
    path('Id_With_price/',views.Id_With_price,name='IdWithprice'),
    
    
    path('admin-login/',views.LoginAdmin,name='loginadmins'),
    path('admin-logout/',views.LogoutAdmin,name='Logoutadin'),
    
    # Map APIs
    path('map-view/',views.map_view,name='mapview'),
    path('in-map-view/',views.Incitymap_view,name='Incitymap_view'),
    path('Directions-View',views.map,name='map'),
    path('map',views.mobile_map,name='mobile_map'),
    path('Incityride_Map',views.Incityride_Map,name='Incityride_Map'),
    path('firebase-messaging-sw.js',views.showFirebaseJS,name="show_firebase_js"),
    
]

project/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin-django/', admin.site.urls),
    path('mobile-api/',include('doxer.urls')),
    path('',include('doxer_admin.urls')),
]

handler404 = 'demo.views.error_404'
handler500 = 'demo.views.error_500'

doxer_admin/models.py
from django.db import models

# Create your models here.

class admin_credentials(models.Model):
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    

doxer_admin/views.py
from django.shortcuts import render,redirect
from django.core.exceptions import *
from django.contrib.auth.hashers import make_password,check_password
from time import strftime
from doxer.models import *
from django.http import JsonResponse,HttpResponseRedirect,HttpResponse
from .models import *
from datetime import datetime
from time import gmtime, strftime
from django.db.models import F, Sum
from django.core.paginator import Paginator,EmptyPage
from time import strftime
from django.views.decorators.csrf import csrf_exempt
from .mixins import Directions
from django.contrib import messages
import re
import requests
import json

# Create your views here.
car_per_page = 10
driver_per_page = 10
passenger_per_page = 10
rides_per_page = 10


def send_notification(registration_ids , message_title , message_desc):
    fcm_api = "AAAArz4KUBo:APA91bGVbwnMSAY90DLP5-4R1n7jBPZaVtqGj6ttqAaOvAJgLDB0cNGLesf4rT06n445NVeM08QNyHqU74nF_OjcRCv0g6PNy_F87qAVbIQPhV1WufUXcggiwvDO-qlc1_D7xkbkSRQ3"
    # fcm_api = settings.FireBase_API_KEY
    url = "https://fcm.googleapis.com/fcm/send"
    
    headers = {
    "Content-Type":"application/json",
    "Authorization": 'key='+fcm_api}

    payload = {
        "registration_ids" :registration_ids,
        "priority" : "high",
        "notification" : {
            "body" : message_desc,
            "title" : message_title,
            "icon": "https://softskillers.ca/mylifto/static/images/doxerlogopush.png",
            # "image" : "https://i.ytimg.com/vi/m5WUPHRgdOA/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDwz-yjKEdwxvKjwMANGk5BedCOXQ",
            
        }
    }

    result = requests.post(url,  data=json.dumps(payload), headers=headers )

def showFirebaseJS(request):
    data='importScripts("https://www.gstatic.com/firebasejs/8.2.0/firebase-app.js");' \
         'importScripts("https://www.gstatic.com/firebasejs/8.2.0/firebase-messaging.js"); ' \
         'var firebaseConfig = {' \
         '        apiKey: "",' \
         '        authDomain: "",' \
         '        databaseURL: "",' \
         '        projectId: "",' \
         '        storageBucket: "",' \
         '        messagingSenderId: "",' \
         '        appId: "",' \
         '        measurementId: ""' \
         ' };' \
         'firebase.initializeApp(firebaseConfig);' \
         'const messaging=firebase.messaging();' \
         'messaging.setBackgroundMessageHandler(function (payload) {' \
         '    console.log(payload);' \
         '    const notification=JSON.parse(payload);' \
         '    const notificationOption={' \
         '        body:notification.body,' \
         '        icon:notification.icon' \
         '    };' \
         '    return self.registration.showNotification(payload.notification.title,notificationOption);' \
         '});'

    return HttpResponse(data,content_type="text/javascript")

@csrf_exempt
def LoginAdmin(request):
    try:
        if request.method == "POST":
            uname = request.POST['Username']
            pswd = request.POST['password']
                
            # user = admin_credentials.objects.create(
            #     username = uname,
            #     password = pswd
            # )
            # user.password = make_password(user.password)
            # user.save()
            # messages.success(request, f"Register Successfully")
            # return redirect("doxer_admin:loginpage")
            user = admin_credentials.objects.filter(username=uname)
            # user = User.objects.filter(username=uname)
            if len(user) > 0:
                pas = check_password(pswd, user[0].password)
                if pas:
                    request.session['id'] = user[0].id
                    return redirect("doxer_admin:indexpage")
                else:
                    messages.error(request, f"Password is Incorrect..!")
                    request.session['uname'] = uname
                    return redirect("doxer_admin:loginpage")
            else:
                messages.error(request, f"{uname} User Not Founded")
                request.session['uname'] = uname
                request.session['pswd'] = pswd
                return redirect("doxer_admin:loginpage")
        else:
            messages.error(request, f"Something Wrong.!")
            return redirect("doxer_admin:loginpage")
    except:
        return redirect('doxer_admin:loginpage')

@csrf_exempt
def home(request):
    if 'id' in request.session:
        if 'uname' in request.session:
            del request.session['uname']
        if 'pswd' in request.session:
            del request.session['pswd']
        showtime = strftime("%Y-%m-%d")
        dri = user_all.objects.filter(as_user='Driver').exclude(active_ac_with_otp='0')
        dri1 = user_all.objects.filter(as_user='Driver',status="Deactive")
        pas = user_all.objects.filter(as_user='Passenger').exclude(active_ac_with_otp='0')
        pas1 = user_all.objects.filter(as_user='Passenger',status="Deactive")
        rid = Ride_pin.objects.filter(pas_status='E',status='1').exclude(status='2')#.aggregate(total=Sum(F('fees')))
        
        thevalue = 0
        for j in rid:
            if j.getride.trip_status == 'E':
                thevalue = thevalue + float(j.fees)

        rid1 = Ride_pin.objects.filter(pas_status='E',status='1',today=showtime).exclude(status='2')#.aggregate(total=Sum(F('fees')))
        
        todayvalue = 0
        for i in rid1:
            if i.getride.trip_status == 'E':
                todayvalue = todayvalue + float(i.fees)
        
        if request.method == 'POST':
            if thevalue == 0:
                income = "00.00"
            else:
                income = format(thevalue, '.2f')
            if todayvalue == 0:
                dayas = "00.00"
            else:
                dayas = format(todayvalue, '.2f')
                
            if 'id' in request.session:
                sess = "1"
            else:
                sess = "0"
            contax = {
                "sess" : sess,
                'dri' : dri.count(),
                'pas' : pas.count(),
                'dri1' : dri1.count(),
                'pas1' : pas1.count(),
                'income' : f"{income}",
                'today' : f"{dayas}",
                }
            return JsonResponse(contax)
        contax = {
            't1' : '1',
            'dri' : dri.count(),
            'pas' : pas.count(),
            'title' : "Home Page"
        }
        # return render(request,'Direction/Direction.html')
        return render(request,'doxer_admin/index.html',contax)
    else:
        return redirect("doxer_admin:loginpage")

@csrf_exempt
def LoginPage(request):
    if 'id' in request.session:
        return redirect('doxer_admin:indexpage')
    else:
        contax = {
            'title' : "Login Page",
        }
        return render(request,'doxer_admin/login.html',contax)

@csrf_exempt
def All_Drivers(request):
    if 'id' in request.session:
        allu = user_all.objects.filter(as_user='Driver').exclude(active_ac_with_otp='0').order_by('-id')
        per_page = driver_per_page
        # Paginator in a view function to paginate a queryset
        # show 4 news per page
        obj_paginator = Paginator(allu, per_page)
        # list of objects on first page
        first_page = obj_paginator.page(1).object_list
        
        page_range =  obj_paginator.page_range
        pages_range = page_range[-1]
        pages = pages_range
        context = {
        'obj_paginator':obj_paginator,
        'first_page':first_page,
        'page_range':page_range,
        'pages' : pages,
        'pages1' : pages-1,
        'a' : 1,
        'b' : 1 * per_page,
        't' : allu.count(),
        't1' : '3',
        'title': "All Drivers Page"
        }
        try:
            if request.method == 'POST':
                #getting page number
                page_no = request.POST.get('page_no', None) 
                starting_number= (int(page_no)-1)*per_page
                ending_number= int(page_no)*per_page
                res = user_all.objects.filter(as_user='Driver').exclude(active_ac_with_otp='0').order_by('-id')[starting_number:ending_number]
                results = []
                for i in res:
                    resa = {}
                    resa['id'] = i.id
                    resa['pro_image'] = i.pro_image.url
                    resa['username'] = i.name.title()
                    resa['email'] = i.email
                    resa['contact_no'] = i.contact_no
                    if i.gender == "M":
                        gender = 'Male'
                    elif i.gender == "F":
                        gender = 'Female'
                    elif i.gender == "O":
                        gender = 'Other'
                    else:
                        gender = ''
                    resa['gender'] = gender
                    resa['id_status'] = i.img_status
                    resa['city'] = i.city.capitalize()
                    resa['fare_per_km'] = format(i.fare_per_km, '.2f')
                    if i.image2 and i.image1:

doxer_admin/templates/home/foot.html
{% load static %}
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © doxer.com 2021 Developed By <a href="https://maquinistas.in/" target="_blank">maquinistas.in</a></span>
    </div>
  </footer>
  <!-- partial -->
</div>
<!-- main-panel ends -->
</div>
<!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->
<!-- plugins:js -->
<script>
//   document.addEventListener('contextmenu', event => event.preventDefault());
</script>
<script>
  function redirect(){
     window.location.href = "/doxer-admin/admin-logout/";
  }
  // setTimeout(redirect, 2000); //2000 is equivalent to 2 seconds
</script>
<div class="container" hidden>
  <div class="display-date">
    <span id="day">day</span>,
    <span id="daynum">00</span>
    <span id="month">month</span>
    <span id="year">0000</span>
  </div>
  <div class="display-time"></div>
</div>
<p id='pdate' hidden><span id='spanyear'></span>-<span id="spanmonth"></span>-<span id='spandd'></span> <span id='spantime'></span></p>
<script>
$( document ).ready(function() {
    const displayTime = document.querySelector(".display-time");
    function showTime() {
    let time = new Date();
    displayTime.innerText = time.toLocaleTimeString("en-US", { hour12: false });
    setTimeout(showTime, 1000);
    }
    
    showTime();
    
    // Date
    function updateDate() {
    let today = new Date();
    
    // return number
    let dayName = today.getDay(),
    dayNum = today.getDate(),
    month = today.getMonth(),
    year = today.getFullYear();
    const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    ];
    const dayWeek = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    ];
    // value -> ID of the html element
    const IDCollection = ["day", "daynum", "month", "year"];
    // return value array with number as a index
    const val = [dayWeek[dayName], dayNum, month, year];
    for (let i = 0; i < IDCollection.length; i++) {
    document.getElementById(IDCollection[i]).firstChild.nodeValue = val[i];
    }
    }
    
    updateDate();

    setInterval(showTime, 1000);
    function showTime() {
    let today = new Date();
    dayName = today.getDay(),
    dayNum = today.getDate(),
    month = today.getMonth(),
    year = today.getFullYear();
    var time = displayTime.innerText = today.toLocaleTimeString("en-US", { hour12: false });
    $("#spandd").text(dayNum);
    $("#spanmonth").text(month);
    $("#spanyear").text(year);
    $("#spantime").text(time);
    var datses = $("#pdate").text();
    $("#Currentdate").val(datses);
    }
});
</script>

<script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'vendors/moment/moment.min.js' %}"></script>
<script src="{% static 'vendors/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'vendors/chartist/chartist.min.js' %}"></script>
<script src="{% static 'vendors/select2/select2.min.js' %}"></script>
<script src="{% static 'vendors/typeahead.js/typeahead.bundle.min.js' %}"></script>
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{% static 'js/off-canvas.js' %}"></script>
<script src="{% static 'js/misc.js' %}"></script>
<!-- endinject -->
<!-- Custom js for this page -->
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="{% static 'js/typeahead.js' %}"></script>
<script src="{% static 'js/select2.js' %}"></script>
<script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script>
  $(document).ready( function () {
    $('#myTable').DataTable();
  } );
</script>
<!-- End custom js for this page -->

doxer_admin/templates/home/head.html
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Lifto | {{title}}</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'vendors/simple-line-icons/css/simple-line-icons.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    
    <script src="https://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.9/gmaps.min.js"></script>
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="{% static 'vendors/daterangepicker/daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/chartist/chartist.min.css' %}">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'images/aaaa.png' %}" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.all.min.js"></script>

    <!-- Bootstrap CSS -->
</head>


doxer_admin/templates/home/header.html
{% load static %}
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="navbar-brand-wrapper d-flex align-items-center">
      <a class="navbar-brand brand-logo" href="javascript:void(0);">  
        <img src="{% static 'images/aaaa.png' %}" alt="logo" class="logo-dark" />
        <!--img src="{% static 'images/doxer-gifs.gif' %}" alt="logo" class="logo-dark" /-->

      </a>
      <a class="navbar-brand brand-logo-mini" href="javascript:void(0);"><img src="{% static 'images/aaaa.png' %}" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center flex-grow-1">
      <!--h5 class="mb-0 font-weight-medium d-none d-lg-flex">Welcome Doxer dashboard!</h5-->
      <ul class="navbar-nav navbar-nav-right ml-auto">
        <form class="search-form d-none d-md-block" action="javascript:void(0);">
          <!--i class="icon-magnifier"></i>
          <input type="search" id="myInput" class="form-control" placeholder="Search Here" title="Search here"-->
        </form>
        <!--li class="nav-item"><a href="#" class="nav-link"><i class="icon-basket-loaded"></i></a></li>
        <li class="nav-item"><a href="#" class="nav-link"><i class="icon-chart"></i></a></li-->
        <!--li class="nav-item dropdown">
          <a class="nav-link count-indicator message-dropdown" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
            <i class="icon-speech"></i>
            <span class="count">7</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="messageDropdown">
            <a class="dropdown-item py-3">
              <p class="mb-0 font-weight-medium float-left">You have 7 unread mails </p>
              <span class="badge badge-pill badge-primary float-right">View all</span>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="{% static 'images/faces/face10.jpg' %}" alt="image" class="img-sm profile-pic">
              </div>
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">Marian Garner </p>
                <p class="font-weight-light small-text"> The meeting is cancelled </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="{% static 'images/faces/face12.jpg' %}" alt="image" class="img-sm profile-pic">
              </div>
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">David Grey </p>
                <p class="font-weight-light small-text"> The meeting is cancelled </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="{% static 'images/faces/face1.jpg' %}" alt="image" class="img-sm profile-pic">
              </div>
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">Travis Jenkins </p>
                <p class="font-weight-light small-text"> The meeting is cancelled </p>
              </div>
            </a>
          </div>
        </li-->
        <!--li class="nav-item dropdown language-dropdown d-none d-sm-flex align-items-center">
          <a class="nav-link d-flex align-items-center dropdown-toggle" id="LanguageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
            <div class="d-inline-flex mr-3">
              <i class="flag-icon flag-icon-us"></i>
            </div>
            <span class="profile-text font-weight-normal">English</span>
          </a>
          <div class="dropdown-menu dropdown-menu-left navbar-dropdown py-2" aria-labelledby="LanguageDropdown">
            <a class="dropdown-item">
              <i class="flag-icon flag-icon-us"></i> English </a>
            <a class="dropdown-item">
              <i class="flag-icon flag-icon-fr"></i> French </a>
            <a class="dropdown-item">
              <i class="flag-icon flag-icon-ae"></i> Arabic </a>
            <a class="dropdown-item">
              <i class="flag-icon flag-icon-ru"></i> Russian </a>
          </div>
        </li-->
        <li class="nav-item dropdown d-none d-xl-inline-flex user-dropdown">
          <a class="dropdown-item log-out-btn" href="{% url 'doxer_admin:Logoutadin' %}"><i class="dropdown-item-icon icon-power text-danger"></i> Sign Out</a>
          <!--a class="nav-link dropdown-toggle" id="UserDropdown" href="javascript:void(0);" data-toggle="dropdown" aria-expanded="false">
            <span class="font-weight-normal"> Admin </span>
            {% comment %} <img class="img-xs rounded-circle ml-2" src="{% static 'images/faces/face8.jpg' %}" alt="Profile image"> <span class="font-weight-normal"> Admin </span></a> {% endcomment %}
          </a-->
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
            <!--div class="dropdown-header text-center">
              <img class="img-md rounded-circle" src="{% static 'images/faces/face8.jpg' %}" alt="Profile image">
              <p class="mb-1 mt-3">Allen Moreno</p>
              <p class="font-weight-light text-muted mb-0">allenmoreno@gmail.com</p>
            </div-->
            <!--a class="dropdown-item"><i class="dropdown-item-icon icon-user text-primary"></i> My Profile <span class="badge badge-pill badge-danger">1</span></a>
            <a class="dropdown-item"><i class="dropdown-item-icon icon-speech text-primary"></i> Messages</a>
            <a class="dropdown-item"><i class="dropdown-item-icon icon-energy text-primary"></i> Activity</a>
            <a class="dropdown-item"><i class="dropdown-item-icon icon-question text-primary"></i> FAQ</a-->
            <a class="dropdown-item" href="{% url 'doxer_admin:Logoutadin' %}"><i class="dropdown-item-icon icon-power text-primary"></i>Sign Out</a>
          </div>
        </li>
      </ul>
      <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
        <span class="icon-menu"></span>
      </button>
    </div>
</nav>

doxer_admin/templates/home/sider.html
{% load static %}
<style>
  
 ul.nav{
    position: fixed;
    width: inherit;
  }
</style>
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <br>
  <br>
  <br>
<ul class="nav">
  <!--li class="nav-item nav-profile">
    <a href="javascript:void(0);" class="nav-link">
      <div class="profile-image">
        <img class="img-xs rounded-circle" src="{% static 'images/faces/face8.jpg' %}" alt="profile image">
        <div class="dot-indicator bg-success"></div>
      </div>
      <div class="text-wrapper">
        <p class="profile-name">Allen Moreno</p>
        <p class="designation">Administrator</p>
      </div>
      <div class="icon-container">
        <i class="icon-bubbles"></i>
        <div class="dot-indicator bg-danger"></div>
      </div>
    </a>
  </li-->

  <li class="nav-item nav-category"><span class="nav-link">Dashboard</span></li>
    <li class="nav-item {% if t1 == '1' %}active {% endif %}">
    <a class="nav-link" href="{% url 'doxer_admin:indexpage' %}">
      <span class="menu-title">Dashboard</span>
      <i class="icon-screen-desktop menu-icon"></i>
    </a>
  </li>
  <li class="nav-item nav-category"><span class="nav-link">Vehicles</span></li>
    <li class="nav-item {% if t1 == '2' %} active {% endif %}">
    <a class="nav-link" href="{% url 'doxer_admin:allcars' %}">
      <span class="menu-title">All Vehicles Entry</span>
      <i class="icon-globe menu-icon"></i>
    </a>
  </li>
    <li class="nav-item {% if t1 == '6' %} active {% endif %}">
    <a class="nav-link" href="{% url 'doxer_admin:manage_brand' tt='Cars' %}">
      <span class="menu-title">Manage Comapany & Model</span>
      <i class="icon-globe menu-icon"></i>
    </a>
  </li>
  <li class="nav-item nav-category"><span class="nav-link">Users</span></li>
  <li class="nav-item {% if t1 == '3' %}active {% endif %}">
    <a class="nav-link" href="{% url 'doxer_admin:alldrivers' %}">
      <span class="menu-title">Drivers</span>
      <i class="icon-layers menu-icon"></i>
    </a>
  </li>
  <li class="nav-item {% if t1 == '4' %}active {% endif %}">
    <a class="nav-link" href="{% url 'doxer_admin:allpassenger' %}">
      <span class="menu-title">Passengers</span>
      <i class="icon-user menu-icon"></i>
    </a>
  </li>
  <li class="nav-item nav-category"><span class="nav-link">Rides</span></li>
    <li class="nav-item {% if t1 == '5' %} active {% endif %}">
    <a class="nav-link" href="{% url 'doxer_admin:allrides' %}">
      <span class="menu-title">All Rides</span>
      <i class="icon-globe menu-icon"></i>
    </a>
  </li>
</ul>
</nav>