demo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('',views.firstpave,name='pass')
]

doxer_admin/urls.py
from django.urls import path
from . import views


app_name = "doxer_admin"

urlpatterns = [
    path('login-page/',views.LoginPage,name='loginpage'),
    path('',views.home,name='indexpage'),
    path('all-drivers/',views.All_Drivers,name='alldrivers'),
    path('all-passengers/',views.All_Passengers,name='allpassenger'),
    path('all-cars/',views.All_Cars,name='allcars'),
    path('all-rides/',views.All_Rides,name='allrides'),
    path('city-rides/',views.with_in_city_Rides,name='cityrides'),
    path('accepted-cars/',views.Accepted_Cars,name='acceptedcar'),
    path('rejected-cars/',views.Rejected_Cars,name='rejectedcar'),
    
    path('manage-brands-&-<str:tt>-Models/',views.manage_brand,name='manage_brand'),
    path('brand-<str:tt>-store/',views.add_brand_store,name='add_brand_store'),
    path('store-<str:tt>-Models/',views.add_vehical_store,name='add_vehical_store'),
    path('delete-<str:tt>-brand/<str:data>/',views.DeteleVehical_brand,name='DeteleVehical_brand'),
    path('delete-<str:tt>-Models/<str:data>/',views.DeteleCar_name,name='DeteleCar_name'),
    
    # path('admin-add-form/',views.Add_Driver_Form,name='driverform'),
    
    path('Car-accepted/',views.car_accept,name='caraccept'),
    path('Car-rejected/',views.car_reject,name='carreject'),
    path('block-unblock-passenger/',views.BlockPassenger,name='blockpas'),
    path('block-unblock-driver/',views.BlockDriver,name='blockdri'),
    path('edit-price/',views.editprice,name='editprices'),
    path('edit-editcar/',views.editcar,name='editcar'),
    path('show-User-ID/<str:pk>',views.Id_proofes,name='showid'),
    path('Approval-ID/<str:pk>',views.Id_Approval,name='Id_Approval'),
    path('update-price/',views.updateprice,name='updatepriceb'),
    path('Id_With_price/',views.Id_With_price,name='IdWithprice'),
    
    
    path('admin-login/',views.LoginAdmin,name='loginadmins'),
    path('admin-logout/',views.LogoutAdmin,name='Logoutadin'),
    
    # Map APIs
    path('map-view/',views.map_view,name='mapview'),
    path('in-map-view/',views.Incitymap_view,name='Incitymap_view'),
    path('Directions-View',views.map,name='map'),
    path('map',views.mobile_map,name='mobile_map'),
    path('Incityride_Map',views.Incityride_Map,name='Incityride_Map'),
    path('firebase-messaging-sw.js',views.showFirebaseJS,name="show_firebase_js"),
    
]

project/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin-django/', admin.site.urls),
    path('mobile-api/',include('doxer.urls')),
    path('',include('doxer_admin.urls')),
]

handler404 = 'demo.views.error_404'
handler500 = 'demo.views.error_500'

demo/models.py
from django.db import models

# Create your models here.

demo/views.py
from django.shortcuts import render

# Create your views here.

def error_404(request, exception):
    return render(request, 'err.html')

def error_500(request, *args, **argv):
    return render(request,'500.html')

demo/templates/err.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 🧨 Not Found</title>
    <link rel="shortcut icon" href="{% static 'images/aaaa.png' %}" />
  </head>
  <style>
 
    /*====================== 404 page =======================*/
    .four_zero_four_bg h1 {
        font-size: 80px;
        text-align: center;
   }
    .page_404 img{
        width:100%;
   }
    .contant_box_404 {
        margin-top: -50px;
        text-align: center;
   }
    .four_zero_four_bg{
        background-image: url(https://cdn.dribbble.com/users/285475/screenshots/2083086/dribbble_1.gif);
        height: 400px;
        background-repeat : no-repeat;

        background-position: center;
   }
    .four_zero_four_bg h1{
        font-size:80px;
   }
    .four_zero_four_bg h3{
        font-size:80px;
   }
    .link_404{
        color: #fff!important;
        padding: 10px 20px;
        background: #39ac31;
        margin: 20px 0;
        display: inline-block;
   }
    .contant_box_404{
        margin-top:-50px;
   }
   body {
    user-select: none;
}

  </style>
  <body>
    <section class="page_404">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 ">
            <div class="col-sm-10 col-sm-offset-1  text-center">
              <div class="four_zero_four_bg">
                <h1 class="text-center ">404</h1>
              </div>
              <div class="contant_box_404">
                <h3 class="h2"> Look like you're lost </h3>
                <p>the page you are looking for not avaible!</p>
                <a href="{% url 'doxer_admin:indexpage' %}" class="link_404">Go to Home</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
  <script>
    {% comment %} document.addEventListener('contextmenu', event => event.preventDefault()); {% endcomment %}
    </script>
</html>