demo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('',views.firstpave,name='pass')
]

doxer_admin/urls.py
from django.urls import path
from . import views


app_name = "doxer_admin"

urlpatterns = [
    path('login-page/',views.LoginPage,name='loginpage'),
    path('',views.home,name='indexpage'),
    path('all-drivers/',views.All_Drivers,name='alldrivers'),
    path('all-passengers/',views.All_Passengers,name='allpassenger'),
    path('all-cars/',views.All_Cars,name='allcars'),
    path('all-rides/',views.All_Rides,name='allrides'),
    path('city-rides/',views.with_in_city_Rides,name='cityrides'),
    path('accepted-cars/',views.Accepted_Cars,name='acceptedcar'),
    path('rejected-cars/',views.Rejected_Cars,name='rejectedcar'),
    
    path('manage-brands-&-<str:tt>-Models/',views.manage_brand,name='manage_brand'),
    path('brand-<str:tt>-store/',views.add_brand_store,name='add_brand_store'),
    path('store-<str:tt>-Models/',views.add_vehical_store,name='add_vehical_store'),
    path('delete-<str:tt>-brand/<str:data>/',views.DeteleVehical_brand,name='DeteleVehical_brand'),
    path('delete-<str:tt>-Models/<str:data>/',views.DeteleCar_name,name='DeteleCar_name'),
    
    # path('admin-add-form/',views.Add_Driver_Form,name='driverform'),
    
    path('Car-accepted/',views.car_accept,name='caraccept'),
    path('Car-rejected/',views.car_reject,name='carreject'),
    path('block-unblock-passenger/',views.BlockPassenger,name='blockpas'),
    path('block-unblock-driver/',views.BlockDriver,name='blockdri'),
    path('edit-price/',views.editprice,name='editprices'),
    path('edit-editcar/',views.editcar,name='editcar'),
    path('show-User-ID/<str:pk>',views.Id_proofes,name='showid'),
    path('Approval-ID/<str:pk>',views.Id_Approval,name='Id_Approval'),
    path('update-price/',views.updateprice,name='updatepriceb'),
    path('Id_With_price/',views.Id_With_price,name='IdWithprice'),
    
    
    path('admin-login/',views.LoginAdmin,name='loginadmins'),
    path('admin-logout/',views.LogoutAdmin,name='Logoutadin'),
    
    # Map APIs
    path('map-view/',views.map_view,name='mapview'),
    path('in-map-view/',views.Incitymap_view,name='Incitymap_view'),
    path('Directions-View',views.map,name='map'),
    path('map',views.mobile_map,name='mobile_map'),
    path('Incityride_Map',views.Incityride_Map,name='Incityride_Map'),
    path('firebase-messaging-sw.js',views.showFirebaseJS,name="show_firebase_js"),
    
]

project/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin-django/', admin.site.urls),
    path('mobile-api/',include('doxer.urls')),
    path('',include('doxer_admin.urls')),
]

handler404 = 'demo.views.error_404'
handler500 = 'demo.views.error_500'

doxer_admin/models.py
from django.db import models

# Create your models here.

class admin_credentials(models.Model):
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    

doxer_admin/views.py
from django.shortcuts import render,redirect
from django.core.exceptions import *
from django.contrib.auth.hashers import make_password,check_password
from time import strftime
from doxer.models import *
from django.http import JsonResponse,HttpResponseRedirect,HttpResponse
from .models import *
from datetime import datetime
from time import gmtime, strftime
from django.db.models import F, Sum
from django.core.paginator import Paginator,EmptyPage
from time import strftime
from django.views.decorators.csrf import csrf_exempt
from .mixins import Directions
from django.contrib import messages
import re
import requests
import json

# Create your views here.
car_per_page = 10
driver_per_page = 10
passenger_per_page = 10
rides_per_page = 10


def send_notification(registration_ids , message_title , message_desc):
    fcm_api = "AAAArz4KUBo:APA91bGVbwnMSAY90DLP5-4R1n7jBPZaVtqGj6ttqAaOvAJgLDB0cNGLesf4rT06n445NVeM08QNyHqU74nF_OjcRCv0g6PNy_F87qAVbIQPhV1WufUXcggiwvDO-qlc1_D7xkbkSRQ3"
    # fcm_api = settings.FireBase_API_KEY
    url = "https://fcm.googleapis.com/fcm/send"
    
    headers = {
    "Content-Type":"application/json",
    "Authorization": 'key='+fcm_api}

    payload = {
        "registration_ids" :registration_ids,
        "priority" : "high",
        "notification" : {
            "body" : message_desc,
            "title" : message_title,
            "icon": "https://softskillers.ca/mylifto/static/images/doxerlogopush.png",
            # "image" : "https://i.ytimg.com/vi/m5WUPHRgdOA/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDwz-yjKEdwxvKjwMANGk5BedCOXQ",
            
        }
    }

    result = requests.post(url,  data=json.dumps(payload), headers=headers )

def showFirebaseJS(request):
    data='importScripts("https://www.gstatic.com/firebasejs/8.2.0/firebase-app.js");' \
         'importScripts("https://www.gstatic.com/firebasejs/8.2.0/firebase-messaging.js"); ' \
         'var firebaseConfig = {' \
         '        apiKey: "",' \
         '        authDomain: "",' \
         '        databaseURL: "",' \
         '        projectId: "",' \
         '        storageBucket: "",' \
         '        messagingSenderId: "",' \
         '        appId: "",' \
         '        measurementId: ""' \
         ' };' \
         'firebase.initializeApp(firebaseConfig);' \
         'const messaging=firebase.messaging();' \
         'messaging.setBackgroundMessageHandler(function (payload) {' \
         '    console.log(payload);' \
         '    const notification=JSON.parse(payload);' \
         '    const notificationOption={' \
         '        body:notification.body,' \
         '        icon:notification.icon' \
         '    };' \
         '    return self.registration.showNotification(payload.notification.title,notificationOption);' \
         '});'

    return HttpResponse(data,content_type="text/javascript")

@csrf_exempt
def LoginAdmin(request):
    try:
        if request.method == "POST":
            uname = request.POST['Username']
            pswd = request.POST['password']
                
            # user = admin_credentials.objects.create(
            #     username = uname,
            #     password = pswd
            # )
            # user.password = make_password(user.password)
            # user.save()
            # messages.success(request, f"Register Successfully")
            # return redirect("doxer_admin:loginpage")
            user = admin_credentials.objects.filter(username=uname)
            # user = User.objects.filter(username=uname)
            if len(user) > 0:
                pas = check_password(pswd, user[0].password)
                if pas:
                    request.session['id'] = user[0].id
                    return redirect("doxer_admin:indexpage")
                else:
                    messages.error(request, f"Password is Incorrect..!")
                    request.session['uname'] = uname
                    return redirect("doxer_admin:loginpage")
            else:
                messages.error(request, f"{uname} User Not Founded")
                request.session['uname'] = uname
                request.session['pswd'] = pswd
                return redirect("doxer_admin:loginpage")
        else:
            messages.error(request, f"Something Wrong.!")
            return redirect("doxer_admin:loginpage")
    except:
        return redirect('doxer_admin:loginpage')

@csrf_exempt
def home(request):
    if 'id' in request.session:
        if 'uname' in request.session:
            del request.session['uname']
        if 'pswd' in request.session:
            del request.session['pswd']
        showtime = strftime("%Y-%m-%d")
        dri = user_all.objects.filter(as_user='Driver').exclude(active_ac_with_otp='0')
        dri1 = user_all.objects.filter(as_user='Driver',status="Deactive")
        pas = user_all.objects.filter(as_user='Passenger').exclude(active_ac_with_otp='0')
        pas1 = user_all.objects.filter(as_user='Passenger',status="Deactive")
        rid = Ride_pin.objects.filter(pas_status='E',status='1').exclude(status='2')#.aggregate(total=Sum(F('fees')))
        
        thevalue = 0
        for j in rid:
            if j.getride.trip_status == 'E':
                thevalue = thevalue + float(j.fees)

        rid1 = Ride_pin.objects.filter(pas_status='E',status='1',today=showtime).exclude(status='2')#.aggregate(total=Sum(F('fees')))
        
        todayvalue = 0
        for i in rid1:
            if i.getride.trip_status == 'E':
                todayvalue = todayvalue + float(i.fees)
        
        if request.method == 'POST':
            if thevalue == 0:
                income = "00.00"
            else:
                income = format(thevalue, '.2f')
            if todayvalue == 0:
                dayas = "00.00"
            else:
                dayas = format(todayvalue, '.2f')
                
            if 'id' in request.session:
                sess = "1"
            else:
                sess = "0"
            contax = {
                "sess" : sess,
                'dri' : dri.count(),
                'pas' : pas.count(),
                'dri1' : dri1.count(),
                'pas1' : pas1.count(),
                'income' : f"{income}",
                'today' : f"{dayas}",
                }
            return JsonResponse(contax)
        contax = {
            't1' : '1',
            'dri' : dri.count(),
            'pas' : pas.count(),
            'title' : "Home Page"
        }
        # return render(request,'Direction/Direction.html')
        return render(request,'doxer_admin/index.html',contax)
    else:
        return redirect("doxer_admin:loginpage")

@csrf_exempt
def LoginPage(request):
    if 'id' in request.session:
        return redirect('doxer_admin:indexpage')
    else:
        contax = {
            'title' : "Login Page",
        }
        return render(request,'doxer_admin/login.html',contax)

@csrf_exempt
def All_Drivers(request):
    if 'id' in request.session:
        allu = user_all.objects.filter(as_user='Driver').exclude(active_ac_with_otp='0').order_by('-id')
        per_page = driver_per_page
        # Paginator in a view function to paginate a queryset
        # show 4 news per page
        obj_paginator = Paginator(allu, per_page)
        # list of objects on first page
        first_page = obj_paginator.page(1).object_list
        
        page_range =  obj_paginator.page_range
        pages_range = page_range[-1]
        pages = pages_range
        context = {
        'obj_paginator':obj_paginator,
        'first_page':first_page,
        'page_range':page_range,
        'pages' : pages,
        'pages1' : pages-1,
        'a' : 1,
        'b' : 1 * per_page,
        't' : allu.count(),
        't1' : '3',
        'title': "All Drivers Page"
        }
        try:
            if request.method == 'POST':
                #getting page number
                page_no = request.POST.get('page_no', None) 
                starting_number= (int(page_no)-1)*per_page
                ending_number= int(page_no)*per_page
                res = user_all.objects.filter(as_user='Driver').exclude(active_ac_with_otp='0').order_by('-id')[starting_number:ending_number]
                results = []
                for i in res:
                    resa = {}
                    resa['id'] = i.id
                    resa['pro_image'] = i.pro_image.url
                    resa['username'] = i.name.title()
                    resa['email'] = i.email
                    resa['contact_no'] = i.contact_no
                    if i.gender == "M":
                        gender = 'Male'
                    elif i.gender == "F":
                        gender = 'Female'
                    elif i.gender == "O":
                        gender = 'Other'
                    else:
                        gender = ''
                    resa['gender'] = gender
                    resa['id_status'] = i.img_status
                    resa['city'] = i.city.capitalize()
                    resa['fare_per_km'] = format(i.fare_per_km, '.2f')
                    if i.image2 and i.image1:

doxer_admin/templates/doxer_admin/acceptecar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'home/head.html' %}
  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:../../partials/_navbar.html -->
      {% include 'home/header.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:../../partials/_sidebar.html -->
        {% include 'home/sider.html' %}
        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"> All Accepted Vehicles </h3>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item" style='color:green;'><b>Vehicles</b></li>
                  <li class="breadcrumb-item active" aria-current="page">Accepted Vehicles</li>
                </ol>
              </nav>
            </div>
            <div class="row">
              <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <ul class="breadcrumb justify-content-center">
                        <li><a class='btn btn-sm btn-primary btn-rounded' href="{% url 'doxer_admin:allcars' %}">Pending</a>&nbsp;</li>
                        <li><a class='btn btn-sm btn-secondary btn-rounded' href='javascript:void(0);'>Accepted</a>&nbsp;</li>
                        <li><a class='btn btn-sm btn-danger btn-rounded' href="{% url 'doxer_admin:rejectedcar' %}">Rejected</a>&nbsp;</li>
                    </ul>
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                            <th class="font-weight-bold"> ID </th>
                            <th class="font-weight-bold"> Accepted Date </th>
                            <th class="font-weight-bold"> Driver's Profile </th>
                            <th class="font-weight-bold"> Vehicle Reg_Number </th>
                            <th class="font-weight-bold"> Vehicle Variant </th>
                            <th class="font-weight-bold"> Vehicle Color </th>
                            <th class="font-weight-bold"> Status </th>
                            {% comment %} <th class="font-weight-bold"><center> Action </center></th> {% endcomment %}
                        </tr>
                      </thead>
                      <tbody id="tests-table">
                        
                      </tbody>
                    </table>
                  </div>
                  <div class="page-header">
                    <p id='entries' class='mb-0'>
                      Showing <a id='et1'> 0  </a> to <a id='et2'> 0 </a> of <a id='totale'> 0 </a> Entries
                    </p>
                    <nav aria-label="breadcrumb">
                      <ul class="pagination justify-content-center" id='credit' current=''>
                      </ul>
                    </nav>
                  </div>
                </div>
              </div>
            </div>
          </div>
      {% include 'home/foot.html' %}
      <script>
        {% include 'ajax/acceptedcar.js' %}
      </script>
  </body>
</html>

doxer_admin/templates/doxer_admin/all_ride.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'home/head.html' %}
    <script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>
  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:../../partials/_navbar.html -->
      {% include 'home/header.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:../../partials/_sidebar.html -->
        {% include 'home/sider.html' %}
        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"> All Rides </h3>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item" style='color:green;'><b>All Rides</b></li>
                  <li class="breadcrumb-item active" aria-current="page">Rides</li>
                </ol>
              </nav>
            </div>
            <div class="row">
              <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <ul class="breadcrumb justify-content-center">
                          <li><a class='btn btn-sm btn-secondary btn-rounded' href='javascript:void(0);'>All Rides</a>&nbsp;</li>
                          <li><a class='btn btn-sm btn-success btn-rounded' href="{% url 'doxer_admin:cityrides' %}">In City</a>&nbsp;</li>
                        </ul>
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                            <th class="font-weight-bold"> ID </th>
                            <th class="font-weight-bold"> Trip Date </th>
                            <th class="font-weight-bold"> Ride Registered At </th>
                            <th class="font-weight-bold"> Driver </th>
                            <th class="font-weight-bold"> Passenger </th>
                            <th class="font-weight-bold"> Vehicle  </th>
                            <th class="font-weight-bold"> Trip Route </th>
                            <th class="font-weight-bold"> Status </th>
                            <th class="font-weight-bold"> Ammount </th>
                            <th class="font-weight-bold"><center> Action </center></th>
                          </tr>
                      </thead>
                      <tbody id="tests-table">
                      </tbody>
                    </table>
                  </div>
                  <input type="hidden" class="geo" id="id-lat-a" value="">
                  <input type="hidden" class="geo" id="id-long-a" value="">
                  <input type="hidden" class="geo" id="id-lat-b" value="">
                  <input type="hidden" class="geo" id="id-long-b" value="">
                  <input type="hidden" class="geo" id="id-rid-a" value="">
                  <input type="hidden" class="geo" id="id-rid-link" value="{% url 'doxer_admin:map' %}">
                  <div class="page-header">
                    <p id='entries' class='mb-0'>
                      Showing <a id='et1'> 0  </a> to <a id='et2'> 0 </a> of <a id='totale'> 0 </a> Entries
                    </p>
                    <nav aria-label="breadcrumb">
                      <ul class="pagination justify-content-center" id='credit' current=''>
                      </ul>
                    </nav>
                </div>
                </div>
              </div>
            </div>
          </div>
          <!-- content-wrapper ends -->
      <!-- partial:../../partials/_footer.html -->
      {% include 'home/foot.html' %}
      <script>
        {% include 'ajax/rides.js' %}
      </script>
      <script>
        {% include 'ajax/map_palce.js' %}
      </script>
  </body>
</html>

doxer_admin/templates/doxer_admin/form-model-add.html
<!DOCTYPE html>
<html lang="en">
  <head> {% include 'home/head.html' %} </head>
  <style>
    #contact_form label {
      text-align: left;
      margin-right: 60%;
      color: red;
    }

    img {
      width: 550px;
      height: 400px;
    }
  </style>
  <body id='bodys'>
    <div class="container-scroller">
      <!-- partial:../../partials/_navbar.html --> {% include 'home/header.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:../../partials/_sidebar.html --> {% include 'home/sider.html' %}
        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"> {{type}} Models Add Forms </h3>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item" style='color:green;'>
                    <b>Add Model Form</b>
                  </li>
                  <li class="breadcrumb-item active" aria-current="page">{{type}}</li>
                </ol>
              </nav>
            </div>
            <div class="row">
              <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                      <ul class="breadcrumb justify-content-end">
                          <li><a class='btn btn-sm btn-success btn-rounded' href="{% url 'doxer_admin:manage_brand' tt=type %}">Back</a>&nbsp;</li>
                        </ul>
                    <div role="alert" id='errormsg'></div> 
                    <!--<h4 class="card-title">All Brands</h4>-->
                      <form class="forms-sample" action="{% url 'doxer_admin:add_vehical_store' tt=type %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                      <div class="form-group">
                        <label for="exampleInputName1">Model Name</label>
                        <input type="text" class="form-control" id="model_name" name="model_name" placeholder="Name">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail3">Select Company Name</label>
                        <select class="form-control" id="company_name" name="company_name">
                          <option selected disabled>Select Company Name</option>
                          {% for i in barnd %}
                          <option value="{{i.id}}">{{i.brand}}</option>
                          {% endfor %}
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="exampleInputCity1">Model Image</label>
                        <input type="file" class="form-control" id="model_image" name="model_image" placeholder="Location">
                      </div>
                      <div class="form-group">
                        <label for="exampleTextarea1">Models Colors</label>
                        <select class="form-control" id="colordrop" multiple name="colordrop">
                          {% for i in colors %}
                            <option value="{{i.id}}">{{i.vehical_color}}</option>
                          {% endfor %}
                        </select>
                      </div>
                      {% if type == "trucks" or type == "Trucks" %}
                      <div class="form-group">
                        <label for="exampleTextarea1">Models Dimension</label>
                        <select class="form-control" id="dimensiondrop" multiple name="dimensiondrop">
                          {% for i in dimension %}
                            <option value="{{i.id}}">{{i.dimension}}</option>
                          {% endfor %}
                        </select>
                      </div>
                      {% else %}
                      <input type="hidden" name="dimensiondrop">
                      {% endif %}
                      <button type="submit" class="btn btn-success mr-2">Submit</button>
                      <button type="reset" class="btn btn-light">Cancel</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:../../partials/_footer.html --> {% include 'home/foot.html' %} 
          <script>
          </script>
  </body>
</html>

doxer_admin/templates/doxer_admin/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% include 'home/head.html' %}
  <body>
    <div class="container-scroller">
      <!-- partial:partials/_navbar.html -->
      {% include 'home/header.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
       {% include 'home/sider.html'  %}
        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            <!-- Quick Action Toolbar Ends-->
            <div class="row">
              <div class="col-md-12 grid-margin">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="d-sm-flex align-items-baseline report-summary-header">
                          <h5 class="font-weight-semibold">Report Summary</h5>
                           <!--span class="ml-auto">Updated Report</span-->
                           <a class="ml-auto btn btn-icons border-0 p-2 refresh_btn" href="javascript:void(0);">
                             <!--div class="spinner-grow text-danger spinner-grow-sm" id='spinnereupdate' role="status">
                                <span class="sr-only">Loading...</span>
                              </div-->
                            </a>
                        </div>
                      </div>
                    </div>
                    <div class="row report-inner-cards-wrapper">
                      <div class=" col-md -6 col-xl report-inner-card">
                        <div class="inner-card-text">
                          <span class="report-title">Total Income</span>
                          <h4 id='income'>₹ 00.00</h4>
                          <span class="report-count">&nbsp;</span>
                        </div>
                        <div class="inner-card-icon bg-success">
                          <i class="icon-graph"></i>
                        </div>
                      </div>
                      <a class="col-md-6 col-xl report-inner-card" href="{% url 'doxer_admin:alldrivers' %}">
                          <div class="inner-card-text">
                            <span class="report-title">Drivers</span>
                            <h4 id='hrdri'>{{dri}}</h4>
                              <span style='color:#cbc5c2;font-size:13px;' class='report-count' id='spandri'>&nbsp;</span>
                          </div>
                          <div class="inner-card-icon bg-danger">
                            <i class="icon-user"></i>
                          </div>
                        </a>
                        <a class="col-md-6 col-xl report-inner-card" href="{% url 'doxer_admin:allpassenger' %}">
                          <div class="inner-card-text">
                            <span class="report-title">Passengers</span>
                            <h4 id='h4pas'>{{pas}}</h4>
                            <span style='color:#cbc5c2;font-size:13px;' class='report-count' id='spanpas'>&nbsp;</span>
                          </div>
                          <div class="inner-card-icon bg-info">
                            <i class="icon-people"></i>
                          </div>
                      </a>
                      <div class="col-md-6 col-xl report-inner-card">
                        <div class="inner-card-text">
                          <span class="report-title">Today's Income</span>
                          <h4 id='h4today'>₹ 00.00</h4>
                          <span class="report-count">&nbsp;</span>
                        </div>
                        <div class="inner-card-icon bg-primary">
                          <i class="icon-calendar"></i>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
    {% include 'home/foot.html' %}
    <script>
      {% include 'ajax/home.js' %}    
    </script>
  </body>
</html>

doxer_admin/templates/doxer_admin/mail.html
{% autoescape off %}
<html>
    <center>
    <p>
        Welcome,&nbsp; <b>{{name}}<b>,
    </p>
    <br>
    <p>Thank you for choosing Your Brand. Use the following OTP to complete your Sign Up procedures. OTP is valid for 2 minutes</p>
    <p>
        {{otp}}
    </p>
    <br>
    </center>
    <h2>Regard,</h2>
    <h4>Swooee Admin</h4>
</html>

<!--html>
    <div style="font-family: Helvetica,Arial,sans-serif;min-width:1000px;overflow:auto;line-height:2">
        <div style="margin:50px auto;width:70%;padding:20px 0">
            <div style="border-bottom:1px solid #eee">
                <a href="" style="font-size:1.4em;color: #00466a;text-decoration:none;font-weight:600">Your Brand</a>
            </div>
            <p style="font-size:1.1em">Hi,{{name}}</p>
            <p>Thank you for choosing Your Brand. Use the following OTP to complete your Sign Up procedures. OTP is valid for 2 minutes</p>
            <h2 style="background: #00466a;margin: 0 auto;width: max-content;padding: 0 10px;color: #fff;border-radius: 4px;">{{otp}}</h2>
            <p style="font-size:0.9em;">Regards,<br />Your Brand</p>
            <hr style="border:none;border-top:1px solid #eee" />
            <div style="float:right;padding:8px 0;color:#aaa;font-size:0.8em;line-height:1;font-weight:300">
                <p>Your Brand Inc</p>
                <p>1600 Amphitheatre Parkway</p>
                <p>California</p>
            </div>
        </div>
    </div>
</html-->
{% endautoescape %}